### ISSUE TITLE
Settings whitelistDB

### ISSUE THREAD

**Issue by illmat** [Meteor-Reaction/CanDo#1]
In method can:
~~~javascript
if (this.whitelistDB && result == 2)
~~~

Shouldn't that be this.settings.whitelistDB?

**Comment by Kestanous** [comment]
Thanks @illmat, good catch. I fixed this in the new code. 

I ended up rewriting most of it and will rename it to "Candid" soon. I have not updated the Readme much but here is whats done: So far I have methods and allow/deny working. The `Can.can` function will not work at all but `Can.authorized` should work. iron:router hooks are next and then I will fix `Can.can`. If you have any thoughts I would love to hear them.
